### ISSUE TITLE
Duration of Waiting Between Two Episodes

### ISSUE THREAD

**Issue by Dadgostar** [rail-berkeley/oxe_envlogger#15]
Hi,

Thanks for your efforts on this great repo!

I'm using this repo to record episodes for a Franka robot with two D435 cameras. Each episode is around 15-20 seconds long. If I set each episode to have its own "tfrecord" file (one "tfrecord" file per episode), is it normal to have around 50-60 seconds of waiting time between episodes to serialize the previous episode?

**Comment by youliangtan** [comment]
From my usecases, it will take some time to serialize the single trajectory, around 15-20s.  Feel free to share if you found a way to "speedup" this process.
