### ISSUE TITLE
Lower-bound number of episodes per shard

### ISSUE THREAD

**Issue by kpertsch** [rail-berkeley/oxe_envlogger#9]
We should probably add a `max(1, ...)` here so that we at least write one episode per shard. I would also set the default opt shard size to 200 and maybe add a factor of 2x to the initial episode size in case it was uncharacteristically short just to be safe.

https://github.com/rail-berkeley/oxe_envlogger/blob/230b76b586cd5b88cd9ffb30eaaa6411dc6f1d7b/oxe_envlogger/envlogger.py#L258

**Comment by youliangtan** [comment]
Resolved in https://github.com/rail-berkeley/oxe_envlogger/commit/7c7c71b768c5f551a73d5471f055c16c9a137eae
